### ISSUE TITLE
No deployment of ghost V4 to heroku

### ISSUE THREAD

**Issue by leder11011** [thelovekesh/ghost-v4-on-heroku#119]
Hello all,

deploying ghost V4 with AWS S3 credentials to heroku gives the following error:
"messageItem could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
"

Please check the issue!

Thanks!

Best regards
Gerrit

**Comment by thelovekesh** [comment]
Please check this discussion - https://github.com/thelovekesh/ghost-v4-on-heroku/discussions/24.

If you face any other issue, feel free to open a new issue.
