### ISSUE TITLE
How to further develop via git after deploying?

### ISSUE THREAD

**Issue by esafwan** [thelovekesh/ghost-v4-on-heroku#15]
When deployed via the button in this repo, I am unable to get the git access to further customize & develop the application. 
For example the command `heroku git:clone -a APP-NAME` returns an empty repo. 

However, as [per doc](https://help.heroku.com/FZDDCBLB/how-can-i-download-my-code-from-heroku), I was able to download code using the below command:

`heroku slugs:download -a APP-NAME`

But the download is not a git repo. What is the right method to continue development once the deployment is done? For example, how can I make changes in the code or install a new plugin or update the version of ghost deployed to heroku via this repo?

**Comment by thelovekesh** [comment]
You do not need to download your code from Heroku. Heroku deployment architecture only provides you an environment to run the code. It does not add or delete anything from your code. If you have deployed a Ghost blog website using the `Deploy` button then you can simply follow the mentioned steps:
1. Git clone this repo.
2. Make the changes/edits to the code according to your needs.
3. Change the remote origin of the repo using the command `heroku git:remote -a [app name]` (in this case your Heroku app git URL)
> Do not forget to change `app name` with your real app name.
4. Push the changes to Heroku

> If you want any help regarding setting up a super-fast publishing platform then you can drop an email at this address - codebulbsio@gmail.com

**Comment by esafwan** [comment]
Thanks for the update.
