### ISSUE TITLE
ER_USER_LIMIT_REACHED: User 'xxxx' has exceeded the 'max_questions' resource (current value: 3600)

### ISSUE THREAD

**Issue by lyrium** [thelovekesh/ghost-v4-on-heroku#16]
Mysql (Jawsdb) on Heroku will ignore connection pool settings to spawn a new connection for every alteration. If you're editing posts on Ghost beyond x amount of time (15m for me), it will exceed the database limit and you're effectively locked out. 

FWIW I'm on a Nextjs front-end, deployed on Vercel. 

I suppose upgrading the database plan might fix this, but a seemingly light activity shouldn't cause this issue to begin with. I would expect needing to upgrade if I was publishing 2-3 blog posts a day, not editing one for two hours 🥲

### Reproduction 
- Add a couple of posts on Ghost 
- EITHER: wait for it to throw the error (which takes me 15-20m), or 
- Read the instance APIs using the same stack 

**EDIT**: I have confirmed that the error goes away when you upgrade the database base plan (I did Kitefin -> Leopard), so it's definitely related to the db limit.

**Comment by thelovekesh** [comment]
This is an issue related to the third part service JAWS DB so marking this issue as closed.
