### ISSUE TITLE
Favicon/publication icon doesn't work

### ISSUE THREAD

**Issue by Byabasaija** [thelovekesh/ghost-v4-on-heroku#18]
I have used this version of ghost on three publications but the favicon/publication icon does not work or does not show up.

**What I have tried already** 
- Adding the favicon via the ghost admin settings panel under branding.
- Adding it via code injection in the {{ head }} section.
- Adding it locally by adding the favicon link tag in the theme itself. 
- Clearing the browser cache, opened the websites from different devices.
- Clearing the build cache for node apps on heroku.
All these have failed to work, I have started thinking this could be an issue with ghost itself though I am not sure. 
When I tried using ghost V3, the favicon was showing, but I cant use it on my publications because it doesn't have some core features I like. 

Any help on resolving this will be highly appreciated. 
Thank you

**Comment by thelovekesh** [comment]
This issue will be solved after updating Ghost to the latest version. So closing this issue.
In case of any other problem, please feel free to open a new issue.
