### ISSUE TITLE
heroku policy won't admit new deploy

### ISSUE THREAD

**Issue by sh3raf** [thelovekesh/ghost-v4-on-heroku#19]
"We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by msaidf** [comment]
just need to fork the repo and push the deploy button from the fork.

**Comment by sh3raf** [comment]
will try asap. Thanks for the advice 👍

**Comment by aldefy** [comment]
unable to do so from fork as well

**Comment by thelovekesh** [comment]
@aldefy @douglaschu Thanks for your patience, I am currently working on this and you might expect the latest release of this repo by today EOD.

Currently, I am closing this issue. If you face any other problem please feel free to open a new issue.
