### ISSUE TITLE
Site creation failing with Salesforce Acceptable Use error

### ISSUE THREAD

**Issue by boxedpaul** [thelovekesh/ghost-v4-on-heroku#27]
When trying to deploy a new site from your button, I get an error in Heroku:

![image](https://user-images.githubusercontent.com/30791738/160227883-e1333ee1-853b-4087-916b-49f26cb1f14c.png)

Is it just me?

**Comment by thelovekesh** [comment]
@boxedpaul Check this [discussion](https://github.com/thelovekesh/ghost-v4-on-heroku/discussions/24). 

Since this question has been answered in the discussion I am closing this. If you have any other questions, please ask your question in discussion with question query.
