### ISSUE TITLE
Deploy to Heroku doesnt work

### ISSUE THREAD

**Issue by joevo2** [thelovekesh/ghost-v4-on-heroku#51]
Heroku auto detect that the code violates their terms of usage and doesnt allow the deployment of this repo

**Comment by dthomason** [comment]
@joevo2 I ran into the same thing until I forked the repo like the docs say.  That got me passed that.  Unfortunately I had it up for about 10 minutes before it got into a crash loop. 😢

**Comment by thelovekesh** [comment]
@joevo2 Check this discussion https://github.com/thelovekesh/ghost-v4-on-heroku/discussions/24

@dthomason Sorry to hear that. Can you please share logs by running `heroku logs -a <appname>` on a new issue? I am closing this one for now.
