### ISSUE TITLE
Could be deployed to Heroku 

### ISSUE THREAD

**Issue by je-guerreroa1-uniandes** [thelovekesh/ghost-v4-on-heroku#54]
Heroku returns the next message, when attempting the deploy:
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
![Screenshot 2022-05-14 at 8 57 44 PM](https://user-images.githubusercontent.com/98400664/168453991-42123697-ac42-4bfe-9b0a-2ec8ef3c1c0c.png)

**Comment by thelovekesh** [comment]
Please check this discussion here - https://github.com/thelovekesh/ghost-v4-on-heroku/issues/51 and be sure to explore closed issues before opening a new ticket based on the same topic.
