### ISSUE TITLE
Unable to clone ghost to local

### ISSUE THREAD

**Issue by nehakumarisaa** [thelovekesh/ghost-v4-on-heroku#8]
Hi,

I was successfully able to create an app with the ghost template. But, when I tried cloning it to my local using the git commands, it gives me an empty repo. How do I get the source code of the heroku app into my GIT?

Can you please help me with this issue?

Thanks,
Neha

**Comment by thelovekesh** [comment]
It's the same source code in the Heroku that you are pushing from this repo. So clone this repo and you will get the same source code as you have in the Heroku.
