### ISSUE TITLE
Client request for 4.8 does not match server version 4.2.2

### ISSUE THREAD

**Issue by telip007** [thelovekesh/ghost-v4-on-heroku#9]
I get this error message `Client request for 4.8 does not match server version 4.2.2` when setting up an app with the deploy button and going to `https://YOURAPPNAME.herokuapp.com/ghost`.

**Comment by thelovekesh** [comment]
Hi! Actually there is a problem with `4.8.X` so I changed the Ghost version for now. You can now deploy the new Ghost instance on Heroku.
